config/routes.rb
Rails.application.routes.draw do

  get 'comments/new'

  get 'sessions/new'

	root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new' 
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get '/tests/:id/start' => 'tests#start'
  post '/tests/:id/start' => 'test#start'
  get '/tests/:id/run/:number' => 'tests#question'
  post '/tests/:id/run/:number' => 'tests#save_answer'
  get '/tests/:id/done' => 'tests#finish'
  get '/courses/:course_id/chapters/:chapter_id/test_lessons/:id/run' => 'test_lessons#run'
  post '/courses/:course_id/chapters/:chapter_id/test_lessons/:id/run' => 'test_lessons#save_answer'

  resources :users
  resources :questions
  resources :tests do
    resources :comments
  end
  resources :courses do
    resources :chapters do
      resources :text_lessons
      resources :test_lessons do
        resources :test_questions
      end
      resources :video_lessons
    end
  end
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
	belongs_to :course
	has_many :text_lessons
	has_many :test_lessons
	has_many :video_lessons
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :test
	belongs_to :user
end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :chapters
end

app/models/option.rb
class Option < ActiveRecord::Base
	belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :options
	has_and_belongs_to_many :tests

	accepts_nested_attributes_for :options
end

app/models/question_option.rb
class QuestionOption < ActiveRecord::Base
  belongs_to :test_question
end

app/models/test.rb
 class Test < ActiveRecord::Base
	has_and_belongs_to_many :questions
	has_many :comments

	serialize :selected_options
end

app/models/test_lesson.rb
class TestLesson < ActiveRecord::Base
  belongs_to :chapter
  has_many :test_questions
end

app/models/test_question.rb
class TestQuestion < ActiveRecord::Base
  belongs_to :test_lesson
  has_many :question_options

  accepts_nested_attributes_for :question_options
end

app/models/text_lesson.rb
class TextLesson < ActiveRecord::Base
  belongs_to :chapter
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
										format: { with: VALID_EMAIL_REGEX },
										uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :comments

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/models/video_lesson.rb
class VideoLesson < ActiveRecord::Base
  belongs_to :chapter
end

app/controllers/test_lessons_controller.rb
class TestLessonsController < ApplicationController

	def show
		@course = Course.find(params[:course_id])
		@chapter = @course.chapters.find(params[:chapter_id])
		@test_lesson = @chapter.test_lessons.find(params[:id])
	end

	def new
		@course = Course.find(params[:course_id])
		@chapter = @course.chapters.find(params[:chapter_id])
		@test_lesson = @chapter.test_lessons.build
	end

	def create
		@course = Course.find(params[:course_id])
		@chapter = @course.chapters.find(params[:chapter_id])
		@test_lesson = @chapter.test_lessons.build(test_lesson_params)
		if @test_lesson.save
			redirect_to [@course, @chapter]
		else
			render 'new'
		end
	end

	def run
		@course = Course.find(params[:course_id])
		@chapter = @course.chapters.find(params[:chapter_id])
		@test_lesson = @chapter.test_lessons.find(params[:id])
		if begin?

		else
			session["tests#{@test_lesson.id}"] = []
		end

		@question_index = session["tests#{@test_lesson.id}"].length

		if @question_index < @test_lesson.test_questions.to_a.length
			@test_question = @test_lesson.test_questions.to_a[@question_index]
			render "question"
		else 
			render "finish"
		end
	end

	def save_answer
		@course = Course.find(params[:course_id])
		@chapter = @course.chapters.find(params[:chapter_id])
		@test_lesson = @chapter.test_lessons.find(params[:id])
		@number = session["tests#{@test_lesson.id}"].length
		@answer = Integer(params[:selected])
		session["tests#{@test_lesson.id}"][@number] = @answer
		run
	end

	def begin?
		not session["tests#{@test_lesson.id}"].nil?
	end

	private
		def test_lesson_params
			params.require(:test_lesson).permit(:name, :description)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis.
	def full_title(page_title = '')
		base_title = 'MaYody Educational'
		if page_title.empty?
			base_title
		else 
			page_title + ' | ' + base_title
		end
	end
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	# Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/test_lessons_helper.rb
module TestLessonsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar for the given user.
	def gravatar_for(user, size = 80, options = {class: "gravatar img-rounded"})
	    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
	    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
	    image_tag(gravatar_url, alt: user.name, class: options[:class])
	end
end

app/views/test_lessons/finish.html.erb
<% @test_lesson.test_questions.to_a.each_with_index do |question, i| %>
	<% q_s_ans = session["tests#{params[:id]}"][i] %>
	<% q_cl_str = (question.right_answer == q_s_ans) ? "panel-success" : "panel-danger" %>
	<div class="col-md-8 col-md-offset-2">
		<%= form_tag  do %>
			<div class = "panel <%= q_cl_str %>">
	   		<div class = "panel-heading">
	      	<h3 class = "panel-title"> <%= question.name %></h3>
	   		</div>
	   
	   		<div class = "panel-body">
	      	<%= question.text %>
	   		</div>
			</div>
			<div class="list-group col-md-10 col-md-offset-1">
				<% question.question_options.to_a.each_with_index do |option, index|%>
				<% li_str = "" %>
				<% li_str = "list-group-item-success" if question.right_answer == index %>
				<% li_str = "list-group-item-danger" if index == q_s_ans && q_s_ans != question.right_answer %>
					<li class="list-group-item <%= li_str %>">
						<%= option.text %>
					</li>
				<% end %>
			</div>
		<% end %>
	</div>
<% end %>
<% session["tests#{params[:id]}"] = nil %>

app/views/test_lessons/new.html.erb
<% provide(:title, "New test") %>

<%= form_for ([@course, @chapter, @test_lesson]) do |f| %>
	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :description %>
		<%= f.text_area :description %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/test_lessons/question.html.erb
<div class="col-md-8 col-md-offset-2">
		<%= form_tag  do %>
			<div class = "panel panel-primary">
	   		<div class = "panel-heading">
	      	<h3 class = "panel-title"> <%= @test_question.name %></h3>
	   		</div>
	   
	   		<div class = "panel-body">
	      	<%= @test_question.text %>
	   		</div>
			</div>
			<div class="form-group">
				<% @test_question.question_options.each_with_index do |option, index|%>
					<div class="row col-md-10 col-md-offset-1">
						<div class="col-md-1">
							<%= radio_button_tag(:selected, index, required: true) %>
						</div>
						<div class="col-md-9">
							<%= label_tag "selected #{index}", option.text %>
						</div>
					</div>
				<% end %>
			</div>
				<%= submit_tag "Answer", class: "btn btn-primary" %>
		<% end %>
	</div>

app/views/test_lessons/run.html.erb
<% provide(:title, @test_lesson.name + ' running') %>

<h1>run</h1>

app/views/test_lessons/show.html.erb
<% provide(:title, @test_lesson.name) %>

<h1><%= @test_lesson.name %></h1>
<p><%= @test_lesson.description %></p>

<%= link_to 'run test', "/courses/#{@course.id}/chapters/#{@chapter.id}/test_lessons/#{@test_lesson.id}/run" %>
<br>
<%= link_to 'add question', new_course_chapter_test_lesson_test_question_path(@course, @chapter, @test_lesson) %>